## intersection gemotry and configurations ##
num_legs: 4
# num_lanes_in_vec: [1, 1, 2, 1]
# num_lanes_out_vec: [3, 1, 1, 1]
num_lanes_in_vec: [2, 2, 2, 2] 
num_lanes_out_vec: [2, 2, 2, 2]
arrival_interval_avg: 2.0
travel_time_range: [3, 6]

## scheduler configurations ##
activate_precedent_offset: true
activate_arrival_time: true # vehicles will be ready at time 0 if false

# tiebreak strategy
# right/left most turns first
tie_minimum_resource_waste_first: true
# high demand lanes first
tie_high_demand_first: true
# splitting resource first
tie_consider_splitting_resource: true
# splitting more resource first
tie_more_splitted_resource_first: true

## testing configurations ##
# negative means system seed
random_seed: 0
test_one_instance: true
test_vehicle_number: 5

## sumo configurations ##
sumo_config_file: "/configs/sumo_intersection/intersection_unregulated.sumocfg"